version: '3.8'

services:
  node: &node
    image: node:12
    volumes:
      - './:/src'
      - 'icu_node_modules:/src/node_modules'
      - 'icu_addon_api_node_modules:/src/addon/api/node_modules'
      - 'icu_addon_auth_node_modules:/src/addon/auth/node_modules'
      - 'icu_addon_rose_node_modules:/src/addon/rose/node_modules'
      - 'icu_ui_core_node_modules:/src/ui/core/node_modules'
    working_dir: /src

  build_production:
    <<: *node
    entrypoint: bash
    command: '-c "yarn install && yarn build:production:ui:core"'

volumes:
  icu_node_modules:
  icu_addon_api_node_modules:
  icu_addon_auth_node_modules:
  icu_addon_rose_node_modules:
  icu_ui_core_node_modules:
